summary: Change user password
tags:
  - 'Authentication'
description: Change the current user's password.
security:
  - bearerAuth: []
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          currentPassword:
            type: string
          newPassword:
            type: string
          confirmPassword:
            type: string
responses:
  '200':
    description: Password changed successfully
