summary: Register user
tags:
  - 'Authentication'
description: Register a new user.
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          name:
            type: string
          email:
            type: string
          password:
            type: string
responses:
  '201':
    description: User registered successfully
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/token.yaml'
