summary: Get current user details
tags:
  - 'User'
description: Retrieve details of the currently authenticated user.
security:
  - bearerAuth: []
responses:
  '200':
    description: Current user details
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/user.yaml'
  '401':
    $ref: '../../components/responses/unauthorized.yaml'
