summary: Get a list of users
tags:
  - 'User'
description: Retrieve a list of users with pagination.
security:
  - bearerAuth: []
parameters:
  - in: query
    name: page
    schema:
      type: integer
    description: Page number
  - in: query
    name: pageSize
    schema:
      type: integer
    description: Items per page
responses:
  '200':
    description: A list of users
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/paginated.yaml'
  '401':
    $ref: '../../components/responses/unauthorized.yaml'
  '403':
    $ref: '../../components/responses/forbidden.yaml'
