openapi: 3.0.3

info:
  title: Simple Dashboard - OpenAPI 3.0
  contact:
    email: luckzivanius@gmail.com
  version: 0.0.0

servers:
  - url: 'https://{url}/api/v1'
    description: Production Server
    variables:
      url:
        default: 'aha-api-kappa.vercel.app'
        description: Production URL
  - url: 'http://localhost:{port}/api/v1'
    description: Local Development Server
    variables:
      port:
        default: '3001'
        description: Production URL

tags:
  - name: User
  - name: Authentication
  - name: Verification

components:
  schemas:
    Error:
      $ref: components/schemas/error.yaml

    Paginated:
      $ref: components/schemas/paginated.yaml

    User:
      $ref: components/schemas/user.yaml

    UserStatistic:
      $ref: components/schemas/user-statistic.yaml

    Token:
      $ref: components/schemas/token.yaml

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /users:
    $ref: routes/users.yaml#/root
  /users/me:
    $ref: routes/users.yaml#/me
  /users/statistic:
    $ref: routes/users.yaml#/statistic

  /users/resend-verification:
    $ref: routes/users.yaml#/resend-verification
  /users/verify:
    $ref: routes/users.yaml#/verify

  /users/password:
    $ref: routes/users.yaml#/password
  /users/password/auth0:
    $ref: routes/users.yaml#/password-auth0

  /auth/login:
    $ref: routes/auth.yaml#/login
  /auth/login/auth0:
    $ref: routes/auth.yaml#/login-with-auth0

  /auth/register:
    $ref: routes/auth.yaml#/register
